language: csharp
solution: WordCounterBot.sln
mono: none
dotnet: 3.0

script:
- dotnet build ./dotnet-app/
after_success:
deploy:
  provider: script
  script: sh ./deploy_to_docker.sh
  on:
    branch: master
    tags: true

services:
 - docker

notifications:
  email:
    on_success: never
    on_failure: always