version: '3.7'
services:
  bot:
    image: admiralwoop/multi-purpose-tg-bot:latest
    ports:
      - "443:443"
    env_file: env
    restart: unless-stopped
    secrets:
      - source: bot-ssl-pfx
        target: /app/ssl.pfx
      - source: bot-ssl-pem
        target: /app/ssl.pem
  db:
    image: postgres:14
    env_file: env
    ports:
      - "35432:5432"
    expose:
      - 5432
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
  certbot:
    image: jkz0/certbot:latest
    environment:
      - ACCOUNT_EMAIL=danilapokhabov@gmail.com
    ports:
      - "80:80"
    volumes:
      - ./domains.json:/conf
      - ./cert/:/certs
    restart: always
secrets:
  bot-ssl-pfx:
    file: ./cert/ssl.pfx
  bot-ssl-pem:
    file: ./cert/ssl.pem
