name: Build

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
     - master

jobs:
  build_and_deploy:
    name: Build an ASP.NET Core app
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build API layer
      run: dotnet build dotnet-app/APIL/WordCounterBot.APIL.WebApi.csproj -c Release -o ./app
